version: '3'
services:
  mongodb:
    image: mongo
    container_name: my-mongodb2
    ports:
      - "27017:27017"
    volumes:
      - ./path/to/mongodb/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
